# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import alive_check_pb2 as alive__check__pb2


class AliveServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealthy = channel.unary_unary(
                '/alivecheck.AliveService/GetHealthy',
                request_serializer=alive__check__pb2.AliveRequest.SerializeToString,
                response_deserializer=alive__check__pb2.AliveResponse.FromString,
                )


class AliveServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHealthy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AliveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealthy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealthy,
                    request_deserializer=alive__check__pb2.AliveRequest.FromString,
                    response_serializer=alive__check__pb2.AliveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alivecheck.AliveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AliveService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHealthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alivecheck.AliveService/GetHealthy',
            alive__check__pb2.AliveRequest.SerializeToString,
            alive__check__pb2.AliveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
